### ISSUE TITLE
Custom documentation example: no snippets displayed when using in comments

### ISSUE THREAD

**Issue by matthias-herrmann** [MiguelYax/ApiDocSnippets#3]
I can call all snippets in my code but when I create a comment manually and try to call a snippet it is not working and the text is only considered as a comment:

`apiSuccess` + Tab is working in code

```
/*
 * apiSuccess snippet not working in comment, no snippet suggestions by vs code
*/
```

How can I call this snippets like in the Custom documentation example in a comment?

**Comment by MiguelYax** [comment]
hi matthias,

You can try this: 

a)  Snippets show in IntelliSense (Ctrl+Space) mixed with other suggestions as well as in a dedicated snippet picker (Insert Snippet in the Command Palette). 

b) Change user or workspace settings  with this configuration for automatic  comment block's suggestions:  
```
 "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": false
    }
```

**Comment by matthias-herrmann** [comment]
@Krazeus ty, I applied the workspace settings
