### ISSUE TITLE
How to get snippets in comments?

### ISSUE THREAD

**Issue by yunlucolin** [MiguelYax/ApiDocSnippets#7]
Hi!
After installing the extension, we can get your snippets in codes, but failed in comment blocks.
``` .js
// okay to get the snippets in codes
apiN => apiName

// failed to get the snippets in comment blocks
/**
* apiN   
*/
```
Should we set some config or install some other extensions?

Thanks!

**Comment by denis-peshkov** [comment]
Hi @ColinLeo,
you have to type:
```
/**
 * apiN   
 */
```
And then press Ctrl+Space. That's it )

**Comment by MiguelYax** [comment]
hi ColinLeo,

You can try this:

a) Snippets show in IntelliSense (Ctrl+Space) mixed with other suggestions as well as in a dedicated snippet picker (Insert Snippet in the Command Palette).

b) Change user or workspace settings with this configuration for automatic comment block's suggestions:

 "editor.quickSuggestions": {
        "other": true,
        "comments": true,
        "strings": false
    }

**Comment by yunlucolin** [comment]
> hi ColinLeo,
> 
> You can try this:
> 
> a) Snippets show in IntelliSense (Ctrl+Space) mixed with other suggestions as well as in a dedicated snippet picker (Insert Snippet in the Command Palette).
> 
> b) Change user or workspace settings with this configuration for automatic comment block's suggestions:
> 
> "editor.quickSuggestions": {
> "other": true,
> "comments": true,
> "strings": false
> }

Thanks for your reply, I make it as b).
