### ISSUE TITLE
can it be used with python files

### ISSUE THREAD

**Issue by maheshgawali** [MiguelYax/ApiDocSnippets#8]
i am using apidocjs with python files for documenting apis, is it possible to use this extension with python files ?

**Comment by denis-peshkov** [comment]
what is the problem? it's just decorators...

**Comment by maheshgawali** [comment]
the autocomplete feature as shown in the snippets doesn't seem to work when editing dosctring (apidocjs format) in python files, hence asked

**Comment by MiguelYax** [comment]
Dear Mahesh; 

Added .py file support. avalible on 0.1.19 version for vscode

**Comment by maheshgawali** [comment]
works now, thanks man.
